const token = {
  VALID:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWNkN2I1Njg3MDEzYTA0MDI0YTRjNyIsInJvbGUiOjEsImlhdCI6MTY2MDYyMTUxNywiZXhwIjoxNjYwNzA3OTE3fQ.Cd63g5slD6cLjdUIL2Gs6dU1Grug6ZGV6_hdJ49xJmQ",
  INVALID:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWNkN2I1Njg3MDEzYTA0MDI0YTRjNyIsInJvbGUiOjEsImlhdCI6MTY2MDUzMTEwNCwiZXhwIjoxNjYwNjE3NTA0fQ.6NjzFg3r5uYQdwPvBhQfGylQp0KMyOJwz3hIksb_shd",
};

module.exports = { token };
